version: "3.7"
services:
  frontend:
    image: fleur75/cakeforu:latest
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    volumes:
      - certbot-certs:/etc/letsencrypt:ro
  backend:
    image: fleur75/cakeforuapi:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  certbot:
    image: certbot/certbot
    command: certonly --webroot --webroot-path=/var/www/html --email fleur75921@gmail.com --agree-tos -d j8a604.p.ssafy.io
    volumes:
      - certbot-certs:/etc/letsencrypt
      - webroot:/var/www/html
    environment:
      - CERTBOT_DOMAIN=j8a604.p.ssafy.io
      - CERTBOT_STAGING=false
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-certs:/etc/letsencrypt:ro
      - nginx-conf:/etc/nginx:ro
      - webroot:/var/www/html
    depends_on:
      - frontend
      - certbot
    command: /bin/sh -c "chmod -R 755 /etc/letsencrypt && nginx -g 'daemon off;'"

volumes:
  certbot-certs:
  webroot:
  mysql_data:
  nginx-conf:
