# ?? URL
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/C4U?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
      open-in-view: false
  messages:
    basename: i18n/exception
    encoding: UTF-8
#    profiles:
#        include: jwt

#logging:
#    level:
#        web: DEBUG
#        org:
#            hibernate:
#                SQL:
#                    DEBUG
#                type:
#                    descriptor:
#                        BasicBinder:
#                            TRACE

jwt.secret: '8sknjlO3NPTBqo319DHLNqsQAfRJEdKsETOds'

## ?? ???
#spring.servlet.multipart.location=C:\\Users\\SSAFY\\Desktop\\proj\\S08P12A504\\yuj-front-end\\public
#spring.servlet.multipart.max-file-size=-1
#spring.servlet.multipart.max-request-size=-1